version: 2.1

jobs:
  build:
    docker:
      - image: 'cimg/go:1.18.4'
    steps:
      - checkout
      - run:
          name: Check GO version
          command: go version 
      - run:
          name: Running build 
          command: cd src && go build && ls -l replaceMe
  docker-build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: building image
          command: docker build -t replaceMe .
      - push-to-docker:
          name: Tagging & pushing to docker
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
              docker tag replaceMe "replaceMe:${CIRCLE_SHA1}"
              docker push "replaceMe:${CIRCLE_SHA1}"
            fi


workflows:
  base-workflow:
    jobs:
      - build:
         name: Running Test and Build

